### PR TITLE
SRE-2608: fixing puppet run for hubot

### PR DESCRIPTION
**Pull request by CYPI**

### CODE REVIEW

**Comment by mhagstrand** [comment]
Any reason you didn't try to update the entire fork rather than hand pick those changes?

**Comment by CYPI** [comment]
I'am not sure what you mean by "update the entire fork". Could you please explain?

**Comment by CYPI** [comment]
Synced Fork from upstream repo

**Comment by CYPI** [comment]
Synced fork from upstream repo

**Comment by CYPI** [comment]
Re-tested it and works as expected. No updates on the dependencies:

```
:~# puppetenv -b fixing_hubot -n
>> Running puppet agent -t --environment fixing_hubot --noop
Info: Retrieving pluginfacts
Info: Retrieving plugin
Notice: /File[/var/lib/puppet/lib/puppet/provider/gpg_key]/ensure: removed
Notice: /File[/var/lib/puppet/lib/puppet/provider/package/pe_gem.rb]/ensure: removed
Notice: /File[/var/lib/puppet/lib/puppet/type/gpg_key.rb]/ensure: removed
Info: Loading facts
Info: Applying configuration version '9cc04b8 - Mon Mar 12 15:05:15 2018 -0700'
Notice: Finished catalog run in 60.17 seconds
```

**Comment by CYPI** [comment]
I re-worked the formatting of package.json to avoid re-installing dependencies at every puppet run.

```
~# puppetenv -b fixing_hubot -f
>> Running puppet agent -t --environment fixing_hubot
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Applying configuration version '3be39d6 - Tue Mar 13 11:18:04 2018 -0700'
Notice: /Stage[main]/Hubot::Config/File[/opt/hubot/hubot/package.json]/content:
--- /opt/hubot/hubot/package.json	2018-03-13 13:23:21.030913771 -0500
+++ /tmp/puppet-file20180313-18370-1p7pgjj	2018-03-13 13:26:12.001738693 -0500
@@ -3,15 +3,9 @@
   "version": "2.8.3",
   "private": true,
   "author": "GitHub Inc.",
-  "keywords": [
-    "github",
-    "hubot",
-    "campfire",
-    "bot"
-  ],
+  "keywords": [ "github", "hubot", "campfire", "bot" ],
   "description": "A simple helpful robot for your Company",
-  "dependencies": {
-    "hubot": ">= 2.6.0 < 3.0.0",
+  "dependencies": { "hubot": ">= 2.6.0 < 3.0.0",
     "hubot-scripts": ">= 2.5.0 < 3.0.0",
     "hubot-hipchat": "~2.5.1-5",
     "moment": "2.19.1",
@@ -41,14 +35,8 @@
     "request": ">= 2.14.0",
     "scraper": "0.0.9",
     "underscore": ">0",
-    "xml2js": "^0.4.6"
-  },
-  "engines": {
-    "node": ">= 0.8.x",
-    "npm": ">= 1.1.x"
-  },
+    "xml2js": "^0.4.6" },
+  "engines": { "node": ">= 0.8.x", "npm":  ">= 1.1.x" },
   "main": "./index",
-  "bin": {
-    "hubot": "./bin/hubot"
-  }
+  "bin": { "hubot": "./bin/hubot" }
 }

Info: Computing checksum on file /opt/hubot/hubot/package.json
Info: FileBucket got a duplicate file {md5}ed694bede18e15fe5737bf378e2747d3
Info: /Stage[main]/Hubot::Config/File[/opt/hubot/hubot/package.json]: Filebucketed /opt/hubot/hubot/package.json to puppet with sum ed694bede18e15fe5737bf378e2747d3
Notice: /Stage[main]/Hubot::Config/File[/opt/hubot/hubot/package.json]/content: content changed '{md5}ed694bede18e15fe5737bf378e2747d3' to '{md5}e546286a1bc0839384eb9521725f48de'
Info: /Stage[main]/Hubot::Config/File[/opt/hubot/hubot/package.json]: Scheduling refresh of Class[Hubot::Service]
Info: Class[Hubot::Config]: Scheduling refresh of Class[Hubot::Service]
Info: Class[Hubot::Service]: Scheduling refresh of Service[hubot]
Notice: /Stage[main]/Hubot::Service/Service[hubot]: Triggered 'refresh' from 1 events
Notice: Finished catalog run in 60.26 seconds
```

**Pull request closed without merging**
